spring:
  application: 
    name: notification

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD}

  cloud:
    stream:
      bindings:
        createdReserveInput:
          destination: created.reserve
          group: notification
          consumer:
            autoBindDlq: true
